### ISSUE TITLE
getting the following error when following the 1st step in the read me 

### ISSUE THREAD

**Issue by davidp234** [JasonM97/Rust-Map-Editor#4]
`Assets/Plugins/Rust.World/FileSystem_AssetBundles.cs(19,32): error CS1070: The type `UnityEngine.AssetBundle' has been forwarded to an assembly that is not referenced. Enable the built in package 'Asset Bundle' in the Package Manager window to fix this error.`
any idea on how to fix this please

thanks
Dave

**Comment by Dezinater** [comment]
Use Unity 2018.1.6f1 or 2018.2.0b7

0b7 is confirmed working 100% of the time
I think Andre is working on a fix to have the Rust.World SDK working on all 2018.2 versions

Do not use 2018.2.0b11. 2018.2.0b10 works for some people.

**Comment by davidp234** [comment]
i have tried it in both and its still not working and more ideas please?

thanks
Dave

**Comment by Dezinater** [comment]
You're using 0b7?

**Comment by davidp234** [comment]
no i have 0b11 i will get an older one thanks 

(edit)
how do i get an older 2018.2

**Comment by davidp234** [comment]
i got it running with 1.6f1 thanks and sorry for wasting time

**Comment by Dezinater** [comment]
No problem 👍
